package snipeit

import "github.com/maxreiter/marksman/pkg/jsonx/optional"

type Permission struct {
	SuperUser                      optional.Type[int] `json:"superuser,omitempty"`
	Admin                          optional.Type[int] `json:"admin,omitempty"`
	Import                         optional.Type[int] `json:"import,omitempty"`
	ViewReports                    optional.Type[int] `json:"reports.view,omitempty"`
	ViewAssets                     optional.Type[int] `json:"assets.view,omitempty"`
	CreateAssets                   optional.Type[int] `json:"assets.create,omitempty"`
	EditAssets                     optional.Type[int] `json:"assets.edit,omitempty"`
	DeleteAssets                   optional.Type[int] `json:"assets.delete,omitempty"`
	CheckinAssets                  optional.Type[int] `json:"assets.checkin,omitempty"`
	CheckoutAssets                 optional.Type[int] `json:"assets.checkout,omitempty"`
	AuditAssets                    optional.Type[int] `json:"assets.audit,omitempty"`
	ViewRequestableAssets          optional.Type[int] `json:"assets.view.requestable,omitempty"`
	ViewAssetEncryptedCustomFields optional.Type[int] `json:"assets.view.encrypted_custom_fields"`
	ViewAccessories                optional.Type[int] `json:"accessories.view,omitempty"`
	CreateAccessories              optional.Type[int] `json:"accessories.create,omitempty"`
	EditAccessories                optional.Type[int] `json:"accessories.edit,omitempty"`
	DeleteAccessories              optional.Type[int] `json:"accessories.delete,omitempty"`
	CheckoutAccessories            optional.Type[int] `json:"accessories.checkout,omitempty"`
	CheckinAccessories             optional.Type[int] `json:"accessories.checkin,omitempty"`
	ModifyAccessoryFiles           optional.Type[int] `json:"accessories.files,omitempty"`
	ViewConsumables                optional.Type[int] `json:"consumables.view,omitempty"`
	CreateConsumables              optional.Type[int] `json:"consumables.create,omitempty"`
	EditConsumables                optional.Type[int] `json:"consumables.edit,omitempty"`
	DeleteConsumables              optional.Type[int] `json:"consumables.delete,omitempty"`
	CheckoutConsumables            optional.Type[int] `json:"consumables.checkout,omitempty"`
	ModifyConsumableFiles          optional.Type[int] `json:"consumables.files,omitempty"`
	ViewLicenses                   optional.Type[int] `json:"licenses.view,omitempty"`
	CreateLicenses                 optional.Type[int] `json:"licenses.create,omitempty"`
	EditLicenses                   optional.Type[int] `json:"licenses.edit,omitempty"`
	DeleteLicenses                 optional.Type[int] `json:"licenses.delete,omitempty"`
	CheckoutLicenses               optional.Type[int] `json:"licenses.checkout,omitempty"`
	ViewLicenseKeys                optional.Type[int] `json:"licenses.keys,omitempty"`
	ModifyLicenseFiles             optional.Type[int] `json:"licenses.files,omitempty"`
	ViewComponents                 optional.Type[int] `json:"components.view,omitempty"`
	CreateComponents               optional.Type[int] `json:"components.create,omitempty"`
	EditComponents                 optional.Type[int] `json:"components.edit,omitempty"`
	DeleteComponents               optional.Type[int] `json:"components.delete,omitempty"`
	CheckoutComponents             optional.Type[int] `json:"components.checkout,omitempty"`
	CheckinComponents              optional.Type[int] `json:"components.checkin,omitempty"`
	ModifyComponentFiles           optional.Type[int] `json:"components.files,omitempty"`
	ViewKits                       optional.Type[int] `json:"kits.view,omitempty"`
	CreateKits                     optional.Type[int] `json:"kits.create,omitempty"`
	EditKits                       optional.Type[int] `json:"kits.edit,omitempty"`
	DeleteKits                     optional.Type[int] `json:"kits.delete,omitempty"`
	ViewUsers                      optional.Type[int] `json:"users.view,omitempty"`
	CreateUsers                    optional.Type[int] `json:"users.create,omitempty"`
	EditUsers                      optional.Type[int] `json:"users.edit,omitempty"`
	DeleteUsers                    optional.Type[int] `json:"users.delete,omitempty"`
	ViewModels                     optional.Type[int] `json:"models.view,omitempty"`
	CreateModels                   optional.Type[int] `json:"models.create,omitempty"`
	EditModels                     optional.Type[int] `json:"models.edit,omitempty"`
	DeleteModels                   optional.Type[int] `json:"models.delete,omitempty"`
	ViewCategories                 optional.Type[int] `json:"categories.view,omitempty"`
	CreateCategories               optional.Type[int] `json:"categories.create,omitempty"`
	EditCategories                 optional.Type[int] `json:"categories.edit,omitempty"`
	DeleteCategories               optional.Type[int] `json:"categories.delete,omitempty"`
	ViewDepartments                optional.Type[int] `json:"departments.view,omitempty"`
	CreateDepartments              optional.Type[int] `json:"departments.create,omitempty"`
	EditDepartments                optional.Type[int] `json:"departments.edit,omitempty"`
	DeleteDepartments              optional.Type[int] `json:"departments.delete,omitempty"`
	ViewStatusLabels               optional.Type[int] `json:"statuslabels.view,omitempty"`
	CreateStatusLabels             optional.Type[int] `json:"statuslabels.create,omitempty"`
	EditStatusLabels               optional.Type[int] `json:"statuslabels.edit,omitempty"`
	DeleteStatusLabels             optional.Type[int] `json:"statuslabels.delete,omitempty"`
	ViewCustomFields               optional.Type[int] `json:"customfields.view,omitempty"`
	CreateCustomFields             optional.Type[int] `json:"customfields.create,omitempty"`
	EditCustomFields               optional.Type[int] `json:"customfields.edit,omitempty"`
	DeleteCustomFields             optional.Type[int] `json:"customfields.delete,omitempty"`
	ViewSuppliers                  optional.Type[int] `json:"suppliers.view,omitempty"`
	CreateSuppliers                optional.Type[int] `json:"suppliers.create,omitempty"`
	EditSuppliers                  optional.Type[int] `json:"suppliers.edit,omitempty"`
	DeleteSuppliers                optional.Type[int] `json:"suppliers.delete,omitempty"`
	ViewManufacturers              optional.Type[int] `json:"manufacturers.view,omitempty"`
	CreateManufacturers            optional.Type[int] `json:"manufacturers.create,omitempty"`
	EditManufacturers              optional.Type[int] `json:"manufacturers.edit,omitempty"`
	DeleteManufacturers            optional.Type[int] `json:"manufacturers.delete,omitempty"`
	ViewDepreciations              optional.Type[int] `json:"depreciations.view,omitempty"`
	CreateDepreciations            optional.Type[int] `json:"depreciations.create,omitempty"`
	EditDepreciations              optional.Type[int] `json:"depreciations.edit,omitempty"`
	DeleteDepreciations            optional.Type[int] `json:"depreciations.delete,omitempty"`
	ViewLocations                  optional.Type[int] `json:"locations.view,omitempty"`
	CreateLocations                optional.Type[int] `json:"locations.create,omitempty"`
	EditLocations                  optional.Type[int] `json:"locations.edit,omitempty"`
	DeleteLocations                optional.Type[int] `json:"locations.delete,omitempty"`
	ViewCompanies                  optional.Type[int] `json:"companies.view,omitempty"`
	CreateCompanies                optional.Type[int] `json:"companies.create,omitempty"`
	EditCompanies                  optional.Type[int] `json:"companies.edit,omitempty"`
	DeleteCompanies                optional.Type[int] `json:"companies.delete,omitempty"`
	CanToggleTwoFactor             optional.Type[int] `json:"self.two_factor,omitempty"`
	CreateAPIKeys                  optional.Type[int] `json:"self.api,omitempty"`
	EditProfileLocation            optional.Type[int] `json:"self.edit_location,omitempty"`
	SelfCheckoutAssets             optional.Type[int] `json:"self.checkout_assets,omitempty"`
	ViewPurchaseCosts              optional.Type[int] `json:"self.view_purchase_cost,omitempty"`
}
