// Generated by LibGen. DO NOT EDIT.
package marksman

import (
	"context"
	"net/http"

	"github.com/maxreiter/marksman/request"
	"github.com/maxreiter/marksman/snipeit"
)

func (c *Client) CreateAccessory(ctx context.Context, options *request.CreateAccessory) (*snipeit.Accessory, error) {
	var payload struct {
		Payload *snipeit.Accessory `json:"payload"`
	}

	return payload.Payload, c.do(ctx, options, &payload, http.MethodPost, "accessories")
}

func (c *Client) CheckInAccessory(ctx context.Context, id int32) (*snipeit.Accessory, error) {
	var payload struct {
		Payload *snipeit.Accessory `json:"payload"`
	}

	return payload.Payload, c.do(ctx, nil, &payload, http.MethodPost, "accessories", id, "checkin")
}

func (c *Client) CheckOutAccessory(ctx context.Context, id int32, options *request.CheckOutAccessory) (*snipeit.Accessory, error) {
	var payload struct {
		Payload *snipeit.Accessory `json:"payload"`
	}

	return payload.Payload, c.do(ctx, options, &payload, http.MethodPost, "accessories", id, "checkout")
}

func (c *Client) PartiallyUpdateAccessory(ctx context.Context, id int32, options *request.PartiallyUpdateAccessory) (*snipeit.Accessory, error) {
	var payload struct {
		Payload *snipeit.Accessory `json:"payload"`
	}

	return payload.Payload, c.do(ctx, options, &payload, http.MethodGet, "accessories", id)
}

func (c *Client) UpdateAccessory(ctx context.Context, id int32, options *request.UpdateAccessory) (*snipeit.Accessory, error) {
	var payload struct {
		Payload *snipeit.Accessory `json:"payload"`
	}

	return payload.Payload, c.do(ctx, options, &payload, http.MethodPut, "accessories", id)
}

func (c *Client) DeleteAccessory(ctx context.Context, id int32) error {
	return c.do(ctx, nil, nil, http.MethodDelete, "accessories")
}

func (c *Client) FetchAccessories(ctx context.Context, options *request.FetchAccessories) ([]snipeit.Accessory, error) {
	var payload struct {
		Rows []snipeit.Accessory `json:"rows"`
	}

	return payload.Rows, c.do(ctx, options, &payload, http.MethodGet, "accessories")
}

func (c *Client) FetchAccessory(ctx context.Context, id int32) (*snipeit.Accessory, error) {
	var payload *snipeit.Accessory

	return payload, c.do(ctx, nil, &payload, http.MethodGet, "accessories", id)
}

func (c *Client) FetchCheckedOutAccessories(ctx context.Context, id int32, options *request.FetchCheckedOutAccessories) ([]snipeit.User, error) {
	var payload struct {
		Rows []snipeit.User `json:"rows"`
	}

	return payload.Rows, c.do(ctx, options, &payload, http.MethodGet, "accessories", id, "checkedout")
}
